export const TOOL_SLUGS = [
    // PDF Tools
    'merge-pdf',
    'split-pdf',
    'compress-pdf',
    'pdf-to-word',
    'pdf-to-images',
    'images-to-pdf',
    'protect-pdf',
    'unlock-pdf',
    'rotate-pdf',
    'grayscale-pdf',
    'watermark-pdf',
    'repair-pdf',
    'extract-images-from-pdf',
    'extract-tables',
    'pdf-diff',
    'booklet-maker',
    'pdf-scrubber',
    'pdf-redactor',
    'pdf-signer',
    'pdf-web-optimize',
    // Image Tools
    'remove-image-background',
    'convert-image',
    'resize-image',
    'compress-image',
    'passport-photo',
    'generate-icons',
    'extract-palette',
    'crop-image',
    'watermark-image',
    'heic-to-jpg'
];
